INSERT INTO CONFIG (
CANHOTO_BORDER,
CANHOTO_FONT,
CANHOTO_HEIGHT,
CANHOTO_PADDING,
CANHOTO_WIDTH,
CURRENTDATE,
LOG_MESSAGES,
PARCELAS,
RECIBO_BORDER,
RECIBO_FONT,
RECIBO_HEIGHT,
RECIBO_PADDING,
RECIBO_WIDTH,
SHOW_FORM_DEBUG,
VER_BOLETO_AUTOMATICAMENTE
)
VALUES('1','130','81','22','10','true','true','12','1','113','81','22','125','true','true');