INSERT INTO ESTADO (sigla,nome) VALUES ('AC','Acre');
INSERT INTO ESTADO (sigla,nome) VALUES ('AL','Alagoas');
INSERT INTO ESTADO (sigla,nome) VALUES ('AM','Amazonas');
INSERT INTO ESTADO (sigla,nome) VALUES ('AP','Amapá');
INSERT INTO ESTADO (sigla,nome) VALUES ('BA','Bahia');
INSERT INTO ESTADO (sigla,nome) VALUES ('CE','Ceará');
INSERT INTO ESTADO (sigla,nome) VALUES ('DF','Distrito Federal');
INSERT INTO ESTADO (sigla,nome) VALUES ('ES','Espiríto Santo');
INSERT INTO ESTADO (sigla,nome) VALUES ('GO','Goiás');
INSERT INTO ESTADO (sigla,nome) VALUES ('MA','Maranhão');
INSERT INTO ESTADO (sigla,nome) VALUES ('MG','Minas Gerais');
INSERT INTO ESTADO (sigla,nome) VALUES ('MS','Mato Grosso do Sul');
INSERT INTO ESTADO (sigla,nome) VALUES ('MT','Mato Grosso');
INSERT INTO ESTADO (sigla,nome) VALUES ('PA','Pará');
INSERT INTO ESTADO (sigla,nome) VALUES ('PB','Paraíba');
INSERT INTO ESTADO (sigla,nome) VALUES ('PE','Pernambuco');
INSERT INTO ESTADO (sigla,nome) VALUES ('PI','Piauí');
INSERT INTO ESTADO (sigla,nome) VALUES ('PR','Paraná');
INSERT INTO ESTADO (sigla,nome) VALUES ('RJ','Rio de Janeiro');
INSERT INTO ESTADO (sigla,nome) VALUES ('RN','Rio Grande do Norte');
INSERT INTO ESTADO (sigla,nome) VALUES ('RO','Rondônia');
INSERT INTO ESTADO (sigla,nome) VALUES ('RR','Roraima');
INSERT INTO ESTADO (sigla,nome) VALUES ('RS','Rio Grande do Sul');
INSERT INTO ESTADO (sigla,nome) VALUES ('SC','Santa Catarina');
INSERT INTO ESTADO (sigla,nome) VALUES ('SE','Sergipe');
INSERT INTO ESTADO (sigla,nome) VALUES ('SP','São Paulo');
INSERT INTO ESTADO (sigla,nome) VALUES ('TO','Tocantins');